### ISSUE TITLE
How do you sign up the first time via the API ?

### ISSUE THREAD

**Issue by pecastro** [gogs/go-gogs-client#101]
Upon fresh install, I've tried POSTing to the /admin/users following the API and I get a 403.
I can't seem to find any documentation on how to setup via the API.

**Comment by Unknwon** [comment]
https://github.com/gogs/docs-api

**Comment by pecastro** [comment]
After disablibg CAPTCHA 

```curl -X POST -i 'http://gogs.wormholenet.local/api/v1/admin/users ' --data '{
    "source_id": 1,
    "login_name": "apiuser",
    "username": "apiuser",
    "email": "apiuser@user.com",
    "password": "password"
}'```

[Macaron] 2019-03-26 23:47:54: Started POST /api/v1/admin/users for 192.168.13.3
[Macaron] 2019-03-26 23:47:54: Completed POST /api/v1/admin/users 403 Forbidden in 458.35?s

**Comment by HectorPascual** [comment]
I'm stuck on this, getting a 403 trying to create a user for the first time, someone can help? I am mounting a system not able to interact with GUI so I must do this via shell commands.
