### ISSUE TITLE
How do you create the first Gogs user via the API ? What's missing?

### ISSUE THREAD

**Issue by pecastro** [gogs/go-gogs-client#102]
Upon fresh install, I've tried POSTing to the /admin/users following the API and I get a 403.
After disabling CAPTCHA

`
curl -X POST -i 'http://gogs/api/v1/admin/users ' --data '{ "source_id": 1, "login_name": "apiuser", "username": "apiuser", "email": "apiuser@user.com", "password": "password" }'
`
```
[Macaron] 2019-03-26 23:47:54: Started POST /api/v1/admin/users for 192.168.13.3
[Macaron] 2019-03-26 23:47:54: Completed POST /api/v1/admin/users 403 Forbidden
```
Is this possible or does Gogs not allow the first user to be create via the API ?

**Comment by Unknwon** [comment]
>How do you create the first Gogs user via the API ? 

You can not.
