### ISSUE TITLE
How to add header in request to webhook

### ISSUE THREAD

**Issue by olaf-meyer** [gogs/go-gogs-client#105]
Hello,

I would like to use a gogs webhook with a destination that requires authentication. Is it possible to add an authentication header to the webhook configuration?

Kind regards,

Olaf

**Comment by Unknwon** [comment]
Hi, currently does no support custom headers in webhook, you can make a proxy that consumes Gogs webhooks then append headers before redirecting.

**Comment by Unknwon** [comment]
But it does feel like a good feature request, would you mind file an issue on the main repository github.com/gogs/gogs? Thank you!
