### ISSUE TITLE
EditIssueTracker does not work

### ISSUE THREAD

**Issue by m-pavel** [gogs/go-gogs-client#111]
API is declared as 'PATCH' but binding will never work because [only PUT and POST](https://github.com/go-macaron/binding/blob/0a927dce40c021625160d9d6d84e8f726457947e/binding.go#L44) expect JSON body.

**Comment by unknwon** [comment]
Hi, thanks for the feedback!

I think the correct fix is to add `PATCH` in https://github.com/go-macaron/binding/blob/0a927dce40c021625160d9d6d84e8f726457947e/binding.go#L44. WDYT?

**Comment by unknwon** [comment]
Hi, I've updated main Gogs repository, PATCH should work on `master` branch now.

**Comment by m-pavel** [comment]
Cool, thanks. 
It's always better to fix from library side.
