### ISSUE TITLE
How to get the attachment of the issue?

### ISSUE THREAD

**Issue by zhantss** [gogs/go-gogs-client#117]
I can't find this api

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by zhantss** [comment]
No, I'm not report a bug, I just want find a API. 
"getting issue attachments", Similar to getting issue comments
Can you help me?

**Comment by unknwon** [comment]
Looking at https://github.com/gogs/docs-api, I don't think it is possible right now.

**Comment by unknwon** [comment]
Related: https://github.com/gogs/go-gogs-client/issues/117

**Comment by zhantss** [comment]
:ok_hand: I get it now, thanks!
