### ISSUE TITLE
Import data from GitLab

### ISSUE THREAD

**Issue by pedromazala** [gogs/go-gogs-client#30]
How can I import a full projeto do gogs? Is that possible?

I want to import Milestones, issues and commits.

**Comment by wilcorrea** [comment]
+1

**Comment by willianmpreis** [comment]
+1

**Comment by gsantner** [comment]
I think this should be reported to gogs itself ;) 
<https://github.com/gogits/gogs/issues>

**Comment by x88** [comment]
+1

**Comment by Unknwon** [comment]
This is never a goal of this repository, closing.
