### ISSUE TITLE
Get public repo without authentication

### ISSUE THREAD

**Issue by Drahoslav7** [gogs/go-gogs-client#60]
It would be really nice, if ```GET /repos/:owner/:repo``` could succeed without authentication for public repos. Similar to issue #23.

**Comment by Corben78** [comment]
Same for organizational repos, the issues, milestones, etc.
As they are visible from the webinterface without authentication, the api should also be able to access them without authentication.

**Comment by Unknwon** [comment]
This should have been fixed already.
