### ISSUE TITLE
How to create organization using gogs API?

### ISSUE THREAD

**Issue by fanux** [gogs/go-gogs-client#77]
I POST to this url, but nothing feedback
```
/api/v1/admin/users/htfang/orgs
{
"username":"htfang",
"full_name":"tttest",
"description":"nothing",
"website":"nothing",
"location":"location"
}
```

**Comment by chdorb** [comment]
https://github.com/gogits/go-gogs-client/wiki/Repositories#create

**Comment by fanux** [comment]
@chdorb sorry, Not repo but orgnization

**Comment by Unknwon** [comment]
This should have been fixed already.

**Comment by yaoAAA** [comment]
hello，I have the same problem.But I fix. In your doc_api create org's path "POST /admin/users/:username/orgs",and in the Parameters is also have a username. 
At first , I think it's the same thing.Finaly ,in th path,the username is the login's username.
In parameters's username is the organizatioin's name, it may me confuse.
Can your change one of the username?
