### ISSUE TITLE
Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.

### ISSUE THREAD

**Issue by js-nj** [gogs/go-gogs-client#91]
I meet a problem when i want to edit one user's information,just as following 

![1](https://user-images.githubusercontent.com/12993862/40306008-90455590-5d2f-11e8-9885-b498c5fe463b.png)
Can you tell me how to fix?

**Comment by Unknwon** [comment]
Set https://github.com/gogs/gogs/blob/master/conf/app.ini#L156 to `*`
