### ISSUE TITLE
Create user when deploying Gogs

### ISSUE THREAD

**Issue by chortels** [gogs/go-gogs-client#96]
Hi, 

I'm trying to automate the creation of a admin user in Gogs but, when I follow the instructions indicated in https://github.com/gogs/go-gogs-client/wiki/Administration-Users, the API returns "403 Forbidden". Why is this happening? Is there any other way to automate the creation of an admin user just after having installed Gogs?

Regards.

**Comment by Unknwon** [comment]
Use CLI to create the first user (which becomes admin automatically):

```
➜  ./gogs admin
NAME:
   Gogs admin - Allow using internal logic of Gogs without hacking into the source code
to make automatic initialization process more smoothly

USAGE:
   Gogs admin command [command options] [arguments...]

COMMANDS:
     create-user                  Create a new user in database
     delete-inactive-users        Delete all inactive accounts
     delete-repository-archives   Delete all repositories archives
     delete-missing-repositories  Delete all repository records that lost Git files
     collect-garbage              Do garbage collection on repositories
     rewrite-authorized-keys      Rewrite '.ssh/authorized_keys' file (caution: non-Gogs keys will be lost)
     resync-hooks                 Resync pre-receive, update and post-receive hooks
     reinit-missing-repositories  Reinitialize all repository records that lost Git files

OPTIONS:
   --help, -h  show help
```

**Comment by lianzxu** [comment]
How do I install gogs CLI? I can't find any info from gogs doc page.

**Comment by unknwon** [comment]
> How do I install gogs CLI? I can't find any info from gogs doc page.

It is the same gogs binary you start the web server.

**Comment by lianzxu** [comment]
Thanks you for the prompt response.

**Comment by russau** [comment]
> which becomes admin automatically

Is this still the case?  I see there is a `--admin` switch now.

**Comment by unknwon** [comment]
> > which becomes admin automatically
> 
> Is this still the case? I see there is a `--admin` switch now.

The first user created on the instance is always the site admin regardless of `--admin` flag. For 2+ users, `--admin` determines whether the user will be promoted to be a site admin.
