### ISSUE TITLE
Getting colloborator is not working 

### ISSUE THREAD

**Issue by nexgenkannan** [gogs/go-gogs-client#99]
Hi ,

Good day!.
I am trying to get the collaborators for my repository with curl command but is it not working. It is giving some html response it is not coming as mentioned in wiki

curl -u "kamal" https://try.gogs.io/api/vi//repos/:kamal/:test/collaborators

Provide your comments on this

**Comment by Unknwon** [comment]
Hi, based on the command you provide, I do not think you've authenticated at all.

**Comment by nexgenkannan** [comment]
Can you please provide the example command for this one , I tried with postman for accessing the values by providing basic authentication there is no results

**Comment by Unknwon** [comment]
If you have read docs, you should know you need use personal access token: https://github.com/gogs/docs-api#authentication
